### ISSUE TITLE
Add legend to graphs on full report

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/mos-energy-benchmark#232]
Add a legend and/or hover interactivity to graphs on the full report page, to indicate what the lines represent.

**Comment by designmatty** [comment]
- Am I adding a legend to the graphs on this page? http://azavea.github.io/mos-energy-benchmark/#!/detail/1155

- And what would be in the content of the legend/hover? I'm unfamiliar with the application so don't know what the lines represent.

**Comment by flibbertigibbet** [comment]
Yes, those are the graphs. I believe the issue is we want to have a way to distinguish between the vertical lines on the graph beyond color, especially since we've added a year. The vertical lines represent different years.

**Comment by designmatty** [comment]
On hover we could display something along these lines:
<img width="462" alt="screen shot 2017-10-16 at 9 54 32 am" src="https://user-images.githubusercontent.com/1928955/31615621-1c04c2a6-b258-11e7-9500-81f9d1289cb8.png">

**Comment by flibbertigibbet** [comment]
Thanks @designmatty. Since the idea is to help the user distinguish which bar is for which year, would it be more helpful to only show the year/value they've hovered over? Or is there some other way to show which one of the three is the hovered value? The color I think should still correspond to the bar's color, for consistency.

**Comment by flibbertigibbet** [comment]
Tried setting `font-weight=bolder` in the popup HTML for the row corresponding to the hovered value, but it seems to be overridden by existing styles elsewhere.

**Comment by designmatty** [comment]
The bolder option isn't working because the font is already at it's boldest. I played around with the font options and it's still difficult to tell them apart. We might use `text-decoration: underline`to highlight the hovered line instead. Thoughts?

**Comment by flibbertigibbet** [comment]
Got the underline working once I moved the style to `_d3-common.scss`:

![underlined_selection](https://user-images.githubusercontent.com/960264/31672244-06797c56-b32a-11e7-8927-495ba9b44987.png)
