### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by jcahail** [azavea/mos-energy-benchmark#259]
![oos logo](https://user-images.githubusercontent.com/24727081/32068708-f2e82818-ba54-11e7-9fb6-e0162f5854e6.jpg)

**Comment by flibbertigibbet** [comment]
To match (more or less) the logos currently in the app, set the background to be transparent and scaled to match the the height on the two logos branded with the office name in the app. (The widths are slightly different).

2x logo:
![logo 2x](https://user-images.githubusercontent.com/960264/32078484-101ed754-ba75-11e7-9e74-f27dcea9bee0.png)

smaller logo:
![logo](https://user-images.githubusercontent.com/960264/32078479-0b457e7c-ba75-11e7-9ee2-e061b37163c1.png)
