### ISSUE TITLE
Label year on Energy Start summary statistic

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/mos-energy-benchmark#263]
On the detail page for a building, the Energy Star score (or Site EUI if there is no Energy Star score) displays in the header. The measurement is for the currently selected year, but is not labeled with the year in the header. Consider adding a year label to the header summary statistic, to make it clear.

**Comment by jcahail** [comment]
@designmatty any chance you could look at this one within the next day or two? Kathryn and I are going to MOS's office on Tuesday to train them on how to make updates.
